docs/dist.yaml, openapi/components/requestBodies/newsItem.yaml, openapi/components/schemas/assessment-item.yaml, openapi/components/schemas/userGroupMembership-readableFields.yaml, openapi/components/schemas/userGroupMembership-writableFields.yaml, openapi/paths/assessment.yaml, openapi/paths/user@{id}@groupMembership@{groupId}.yaml
=> API doc missing mandatory marks [SA-14172]

docs/dist.yaml, openapi/paths/storage@asyncUpload.php.yaml
This has existed since 22.0, but hasn't been documented.
=> Add expiryDate to file upload API [SA-14126]

.github/actions/publish-design.yml
Since the build is based on develop, I need to trigger based on develop changes.
=> Trigger this on develop for now [SA-14289]

.github/workflows/publish-design.yml, .github/workflows/publish-spec-develop.yml, .github/workflows/publish-spec-master.yml
* fix names
* don't attempt to publish spec on branch changes, only on specific tags
=> More workflow fixes [SA-14289]

.github/workflows/publish-design.yml, .github/workflows/publish-spec-develop.yml, .github/workflows/publish-spec-master.yml
Otherwise, the script can't check them out later.
=> Checkout gh-pages first [SA-14289]

.github/workflows/publish-spec-develop.yml, .github/workflows/publish-spec-master.yml
This branch will always have the most up-to-date builds list.
=> Build docs in gh-pages branch [SA-14289]

.github/workflows/publish-design.yml, .github/workflows/publish-spec-develop.yml, .github/workflows/publish-spec-master.yml, .github/workflows/unpublish-spec.yml
Required so that tags on master can trigger a build?
=> Add workflows to master [SA-14289]

openapi/paths/evidence@user@{id}@create.yaml
=> update Create Learning moment status code [SA-14414] (develop)

docs/dist.yaml, openapi/components/schemas/assessment-feedback-item.yaml, openapi/components/schemas/assessment-feedback-list.yaml, openapi/components/schemas/assessment-item.yaml, openapi/components/schemas/assessment-rubric-feedback.yaml, openapi/components/schemas/assessment-rubric.yaml
cleaner version of https://github.com/alaress/schoolbox-api-docs/pull/45/
=> Added Rubric to Assessment API [SA-14039] (develop)

openapi/components/schemas/user-fields.yaml
This reverts commit f859fa4073a92a367801b49dfc619db691fef213.
(This commit references something which is not yet removed in master.)
=> Revert "Remove reference to isBoarder (deleted property) [SA-14766]"

openapi/components/responses/curriculumNodeUsage-list.yaml, openapi/components/schemas/curriculumNodeUsage-courseItem.yaml, openapi/components/schemas/curriculumNodeUsage-folderItem.yaml, openapi/components/schemas/curriculumNodeUsage-list.yaml, openapi/components/schemas/curriculumNodeUsage-unitItem.yaml, openapi/openapi.yaml, openapi/paths/api@curriculum@usage@{id}.yaml
API docs for https://github.com/alaress/schoolbox/pull/27395
=> Curriculum node usage API docs [SA-15038]

openapi/components/schemas/badgeItem.yaml, openapi/components/schemas/curriculumNodeUsage-badgeItem.yaml
also de duped the badge object in the docs
=> add full badge object to curriculum usage response [SA-15192] (develop)

openapi/openapi.yaml
Reverts alaress/schoolbox-api-docs#102
See #109 for why
=> Revert "Add description for why docs have changed so much [SA-14580] (develop)"

openapi/components/responses/userGroupMembership-list.yaml, openapi/components/schemas/user-readableFields.yaml
=> Set schema to array of items instead of single item [SA-15481] develop

openapi/components/responses/evidence-list.yaml, openapi/components/schemas/badgeAwardList.yaml, openapi/components/schemas/dueWorkFeedbackList.yaml, openapi/components/schemas/evidenceList.yaml, openapi/components/schemas/listMetadata.yaml
=> Fixing evidence feed response schema [SA-15579]

openapi/components/schemas/assessment-item.yaml
See comments in corresponding PR for 'develop' (https://github.com/alaress/schoolbox-api-docs/pull/120).
=> Update API docs to match actual responses [SA-15583] master

openapi/components/schemas/curriculumNodeUsage-assessmentItem.yaml
Companion PR to https://github.com/alaress/schoolbox/pull/28947
=> Use lti as assessment type for curriculum nodes, add lessonPlan too [SA-15755]

openapi/components/schemas/calendarAttendance.yaml, openapi/components/schemas/calendarAttendanceStatus.yaml, openapi/components/schemas/discussionComment-read.yaml, openapi/components/schemas/discussionThread-read.yaml, openapi/components/schemas/news/commonFields.yaml, openapi/components/schemas/news/links.yaml, openapi/paths/news@saved@{id}@remove.yaml
=> Fixing mistakes in documents [SA-15356] (develop)

openapi/components/examples/search/result.yaml, openapi/components/schemas/search/pageSubResult-item.yaml, openapi/components/schemas/search/resultTypes/assessment.yaml
A few fixes to match changes made recently to the schoolbox code that generates the search responses.
=> Minor changes to API docs for search [SA-16015-3] develop

openapi/paths/resource@file@{fileId}@ajax.yaml
The behaviour has been changed when the manage all files page is introduced.
=> This path accepts "hidden" only. [SA-15214] (master)

openapi/paths/resource@file@{fileId}@ajax.yaml
=> This path accepts "hidden" only. [SA-15214] (develop)

openapi/components/schemas/user-readableFields.yaml, openapi/components/schemas/userShort.yaml
See comments in corresponding PR for develop (https://github.com/alaress/schoolbox-api-docs/pull/144).
=> Update docs for impersonableUsers to match actual output [SA-17004] master

openapi/components/examples/course-listEmpty.yaml, openapi/components/examples/course-listMultiple.yaml, openapi/components/examples/course-listNoSuggestion.yaml, openapi/components/responses/course-list.yaml, openapi/components/schemas/course-list.yaml, openapi/components/schemas/courseFolderCurriculumItem.yaml, openapi/components/schemas/courseFolderItem.yaml, openapi/components/schemas/courseItem.yaml, openapi/components/schemas/curriculumNodeUsage-courseItem.yaml, openapi/components/schemas/curriculumNodeUsage-folderItem.yaml, openapi/openapi.yaml, openapi/paths/api@courses.yaml
Adding the doc for the new Course Api Endpoint for searching Courses
=> Updating api docs for new Course API endpoint [SA-18484]

openapi/components/parameters/limit.yaml, openapi/paths/assessment.yaml
This PR documents changes made in https://github.com/alaress/schoolbox/pull/31621.
=> Document assessment API max limit [SA-18726] master

openapi/paths/assessment.yaml
See comments in corresponding PR for master (https://github.com/alaress/schoolbox-api-docs/pull/165).
=> Show two options for items in folder array [SA-18729] develop

openapi/components/responses/event-item.yaml, openapi/components/schemas/calendar/eventCommonProps.yaml
See https://github.com/alaress/schoolbox-api-docs/pull/167
=> show actual / correct repeat_until date formats [SA-19233] (develop)
