.github/actions/publish-design.yml
.github/actions/publish-spec-develop.yml
.github/actions/publish-spec-master.yml
.github/actions/publish-spec.yml
.gitignore
package.json
scripts/addBuild.js
scripts/rebuildBuildsList.js

This PR adds three Github actions for publishing changes to api.schoolbox.com.au:
This action is intended for when changes are made to the documentation's frontend assets (e.g. images, CSS, HTML): it listens for changes to the `master` branch's `docs` folder, and copies said changes to the `gh-pages` branch.
Currently there is no NPM build step here, as the frontend assets don't require a build step: they are served directly as is.
This action is intended for when a new Schoolbox production release is created, and thus a new version of the API specification should be made available.
This action listens for new tags on the `master` branch: on a new tag being created, it
* builds the OpenAPI spec from the current `master` branch
* creates a new dropdown option for that tag in the published …

Write Github actions for publishing specs [SA-14289]

---

.github/workflows/publish-design.yml
.github/workflows/publish-spec-develop.yml
.github/workflows/publish-spec-master.yml

* copy hidden files (excl. `.git`, .`.github`) to `gh-pages` on design change
* trigger spec build on release instead of on tag

More updates to build process [SA-14289]

---

docs/dist.yaml
openapi/paths/api@user@{id}@notify.yaml
openapi/paths/assessment.yaml
openapi/paths/assessment@{id}.yaml

User Notify and the Assessment API endpoints require the user to be a superuser.
This updates this in the docs
Bonus: Assessment API `filter[yearLevel][name]` should be `(string)` not int

Label Superuser endpoints with correct perms [SA-14636] (develop)

---

docs/index.html
docs/old.html

This makes the new API docs current, and the current docs old.
- https://api.schoolbox.com.au/new.html => https://api.schoolbox.com.au/
- https://api.schoolbox.com.au/ => https://api.schoolbox.com.au/old.html

Move new docs to current, current to old [SA-14289]

---

openapi/paths/user@{id}.yaml
package.json

This change will allow the requesting user to view information about themselves in addition to the existing functionality of superusers current ability to view all users

updated perm note for userGet endpoint [SA-14774] (develop)

---

README.md
openapi/components/schemas/user-fields.yaml

Note that the change to README.md is unrelated to the removal of the 'boarder leave' module.  I just noticed that that text was out of date, and so fixed it.
Question for the reviewer:
* There is a file named residentialHouse.yaml in openapi/components/schemas that I think might be related to the boarder leave system.  Should this file be removed?

Remove references to deleted module 'boarder leave' [SA-14766] develop

---

openapi/components/responses/curriculumNodeUsage-list.yaml
openapi/components/schemas/curriculumNodeUsage-courseItem.yaml
openapi/components/schemas/curriculumNodeUsage-folderItem.yaml
openapi/components/schemas/curriculumNodeUsage-list.yaml
openapi/components/schemas/curriculumNodeUsage-unitItem.yaml
openapi/openapi.yaml
openapi/paths/api@curriculum@usage@{id}.yaml

Built upon #95, and built to match https://github.com/alaress/schoolbox/pull/27427
The usage docs now contain the course's folder, and the unit's course (which itself now contains a folder).
I would've updated the curriculum API docs, but docs for the curriculum API don't exist!

Update curriculum node usage API docs [SA-15037]

---

openapi/openapi.yaml

Reverts alaress/schoolbox-api-docs#101
As mentioned below:
```
```
So I'm doing just that.

Revert "Add description for why docs have changed so much [SA-14580]"

---

openapi/components/schemas/assessment-item.yaml

This PR replaces https://github.com/alaress/schoolbox-api-docs/pull/118.
dueWork:
lessonPlan:
project:
quiz:
task:

Update API docs to match actual responses [SA-15583] develop

---

docs/index.html

Schoolbox's API docs continue to function as before with this change in place.
Making API requests via these docs doesn't function, but it didn't even without a CSP header: there's a CORS policy on Schoolbox instances which prevents these requests currently?

Add CSP meta tag [SA-16123]

---

openapi/components/schemas/calendarAttendance.yaml
openapi/components/schemas/search/resultTypes/common.yaml
package-lock.json
package.json

Turns out that more recent redocly versions complain about `nullable` if it's not directly within a `type: object` definition, even if it's part of an `allOf` whose other part is also an object. Simple fix though.
I've also updated redocly to a 1.0 production version.

Fix nullable definitions [SA-16016]

---

openapi/components/parameters/search/filter.yaml

This is to update the API docs following the changes made in https://github.com/alaress/schoolbox/pull/29231.
Note below the filter 'from' and 'to' dates are now specified as YYYY-MM-DD.

Update search filter date format to YYYY-MM-DD [SA-16563-3] develop

---

openapi/components/schemas/user-readableFields.yaml
openapi/components/schemas/userShort.yaml

This PR updates the API docs for impersonable users to match the actual ouptut as of https://github.com/alaress/schoolbox/pull/29686.
Schema:
Example:
Schema:
Example:

Update docs for impersonableUsers to match actual output [SA-17004] develop

---

openapi/components/parameters/limit.yaml
openapi/paths/assessment.yaml

See comments in corresponding PR for master (https://github.com/alaress/schoolbox-api-docs/pull/159).

Document assessment API max limit [SA-18726]

---

openapi/components/parameters/limit.yaml

This PR removes a redundant description in limit.yaml.  That file is now structured like id.yaml, and jwt.yaml, and key.yaml - as it should be.
Before:
After:

Remove redundant description for 'limit' param [SA-19198] master

---

openapi/components/parameters/limit.yaml

See comments in corresponding PR for master (https://github.com/alaress/schoolbox-api-docs/pull/163).

Remove redundant description for 'limit' param [SA-19198] develop

---

openapi/components/responses/event-item.yaml
openapi/components/schemas/calendar/eventCommonProps.yaml

we don't allow time in this field no `RFC3339` allowed:
Fixed to show what we actually allow:

show actual / correct repeat_until date formats [SA-19233] (master)

---

openapi/openapi.yaml
openapi/paths/calendar@event@attendance@{id}.yaml
openapi/paths/calendar@event@attendance@{id}@accept.yaml
openapi/paths/calendar@event@attendance@{id}@create.yaml
openapi/paths/calendar@event@attendance@{id}@decline.yaml
openapi/paths/calendar@event@attendance@{id}@delete.yaml
openapi/paths/calendar@event@create.yaml
openapi/paths/calendar@event@{id}@delete.yaml
openapi/paths/calendar@event@{id}@modify.yaml
openapi/paths/calendar@event@{id}@move.yaml

This removes the errant `Event` section.
These sections are grouped by the `tags` node, so having `tags: [calendar, event]` creates two sections - one called Calendar and another called Event - with the exact same contents in each. I'm not sure why someone would try to intentionally dupe those in this manner.
Anyway, I've combined them into the Calendar section. The maintenance of calendar events and the invitations to/attendances thereof, are (to me) still logically classified under Calendar.
If you wanted _event attendance_ specifically in its own section, you could still do that: but you have to make sure that only the attendance yamls use the `event` tag, not just proliferate it everywhere blindly.
```
calendar@event@attendance@{id}.yaml
get:
operationId: getCalendarEventAttendance …
```

Unify Calendar and Event sections [SA-19565] (master)

---

openapi/paths/assessment.yaml

This PR improves the examples given for the Assessments API in the API documentation.  See Jira ticket description for reasons.
Before:
After:

Improve examples for Assessments API [SA-20132] master

---

openapi/components/requestBodies/userNotify.yaml

This just adds `messageParams` to `post /api/user/{id}/notify`:

Add messageParams to release notes [SA-19820]
